### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by Jkk326** [LeandroTheDev/spawners_api#4]
When in conjunction with Battle Towers, breaking the Boss Deep Drifter Spawner causes a crash. Log Below

Running on 64 bit Windows 10.0.19045.0 with 32693 MB RAM
Game Version: v1.19.8 (Stable)
2024-11-11 10:38:42 PM: Critical error occurred in the following mod: spawnersapi@1.1.1
Loaded Mods: ancientarmory@1.0.1, buzzwords@1.7.0, chiseltools@1.12.3, extrachests@1.8.0, moreclay@1.0.1, moremolds@1.4.2, MoreTorchHolders@1.0.0, nailsmold@1.0.1, nocharcoallost@1.0.0, quicklimepk@1.0.0, ragnamans-seeds-from-crops-recipes@1.0.0, rpgitemrarityreborn@1.0.5, thatchexpanded@1.1.1, easytorchlight@1.0.0, usefuldrifterloot@1.1.0, game@1.19.8, animalcages@3.0.2, apewindows@1.0.0, beehivekiln@1.5.1, betterfirepit@1.1.4, betterruins@0.3.9, commonlib@2.3.7, compostgrass@1.2.2, hudclock@3.4.0, knapster@2.9.4, krpgenchantment@0.3.8, levelup@1.2.1, moondroptweaks@1.0.2, nohandsfp@1.0.1, oregolems@0.1.1, rivers@3.1.0, spawnersapi@1.1.1, stickemup@1.1.0, th3dungeon@0.2.1, creative@1.19.8, survival@1.19.8, vsvillage@1.0.0-pre.2, battletowers@1.0.5, tradercamps@1.1.4, extraoverlays@1.4.0, morefloors@2.1.1, stonequarry@3.2.1, xinvtweaks@1.6.2
System.Exception: Can't create itemstack without item!
   at Vintagestory.API.Common.ItemStack..ctor(Item item, Int32 stacksize) in VintagestoryApi\Common\Collectible\ItemStack.cs:line 225
   at SpawnersAPI.Spawner.GetItemDrops() in /home/bobs/Templates/Vintage/SpawnersAPI/SpawnersAPI/Shared/Spawner.cs:line 552
   at SpawnersAPI.Spawner.OnBlockBroken(IPlayer byPlayer) in /home/bobs/Templates/Vintage/SpawnersAPI/SpawnersAPI/Shared/Spawner.cs:line 499
   at Vintagestory.API.Common.Block.OnBlockBroken(IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Block\Block.cs:line 1034
   at Vintagestory.API.Common.CollectibleObject.OnBlockBrokenWith(IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier) in VintagestoryApi\Common\Collectible\Collectible.cs:line 581
   at Vintagestory.Client.NoObf.ClientMain.OnPlayerTryDestroyBlock(BlockSelection blockSelection) in VintagestoryLib\Client\ClientMain.cs:line 1687
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.ContinueBreakSurvival(BlockSelection blockSelection, Block block, Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 795
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected_Patch1(SystemMouseInWorldInteractions this, Single dt)
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2024-11-10 12:18:45 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4957, time stamp: 0xc5225d0f
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x4140
Faulting application start time: 0x01db33acaed25d03
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 401272ae-d82d-45ef-b46d-ba5491f6bac6
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-09-22 7:36:23 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: coreclr.dll, version: 7.0.2024.26716, time stamp: 0x6647966b
Exception code: 0xc0000005
Fault offset: 0x00000000001b5988
Faulting process id: 0x4088
Faulting application start time: 0x01db0d60867a1f71
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.20\coreclr.dll
Report Id: 04d03de9-894c-4b8c-99ab-df8f7f03a709
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 2024-09-01 5:43:04 AM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.8.0, time stamp: 0x661e0000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4717, time stamp: 0x16b0a901
Exception code: 0xe0434352
Fault offset: 0x000000000003b699
Faulting process id: 0x2df4
Faulting application start time: 0x01dafc55825636e9
Faulting application path: E:\Vintagestory\Vintagestory.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ddcdbf90-5b5e-41eb-840e-29add898c72b
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by LeansBoboDev** [comment]
Fixed in 1.1.2
